# Generated by Django 5.2.8 on 2025-11-26 16:23

import django.db.models.deletion
import galleries.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('gallery_type', models.CharField(choices=[('BESTOF', 'Best Of'), ('BW', 'Noir & Blanc'), ('STREETS', 'Street Photography'), ('EXPLORE', 'Exploration'), ('PORTRAIT', 'Portrait'), ('MARIAGE', 'Mariage'), ('BAPTEME', 'Baptême'), ('ANNIVERSAIRE', 'Anniversaire'), ('FAMILLE', 'Famille'), ('PROFESSIONNEL', 'Professionnel'), ('EVENEMENT', 'Événement'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('event_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, max_length=255)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Publique'), ('PRIVATE', 'Privée')], default='PUBLIC', max_length=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='galleries/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('allow_download', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_galleries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Galerie',
                'verbose_name_plural': 'Galeries',
                'ordering': ['-is_featured', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=galleries.models.gallery_image_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=galleries.models.thumbnail_path)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('camera', models.CharField(blank=True, max_length=100)),
                ('lens', models.CharField(blank=True, max_length=100)),
                ('focal_length', models.CharField(blank=True, max_length=50)),
                ('aperture', models.CharField(blank=True, max_length=20)),
                ('shutter_speed', models.CharField(blank=True, max_length=20)),
                ('iso', models.PositiveIntegerField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='galleries.gallery')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['display_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='gallery_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Groupe d'utilisateurs",
                'verbose_name_plural': "Groupes d'utilisateurs",
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groupes autorisés à voir cette galerie privée', related_name='accessible_galleries', to='galleries.usergroup'),
        ),
    ]
