# Generated by Django 5.2.8 on 2025-11-26 18:01

from django.db import migrations, models


def migrate_gallery_to_galleries(apps, schema_editor):
    """Migrate ForeignKey data to ManyToMany."""
    Image = apps.get_model('galleries', 'Image')
    for image in Image.objects.all():
        if hasattr(image, 'gallery_id') and image.gallery_id:
            image.galleries.add(image.gallery_id)


def reverse_migration(apps, schema_editor):
    """Reverse: take first gallery from M2M and set as FK."""
    Image = apps.get_model('galleries', 'Image')
    for image in Image.objects.all():
        first_gallery = image.galleries.first()
        if first_gallery:
            image.gallery_id = first_gallery.id
            image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        # 1. Add the new M2M field first
        migrations.AddField(
            model_name='image',
            name='galleries',
            field=models.ManyToManyField(blank=True, related_name='images_new', to='galleries.gallery'),
        ),
        # 2. Migrate data from FK to M2M
        migrations.RunPython(migrate_gallery_to_galleries, reverse_migration),
        # 3. Remove the old FK field
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
        # 4. Fix the related_name
        migrations.AlterField(
            model_name='image',
            name='galleries',
            field=models.ManyToManyField(blank=True, related_name='images', to='galleries.gallery'),
        ),
    ]
