# Generated by Django 5.2.10 on 2026-01-18 20:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_image_multiple_galleries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, help_text="Notes ou demandes spéciales de l'utilisateur", verbose_name='Notes')),
                ('admin_notes', models.TextField(blank=True, help_text="Notes internes (non visibles par l'utilisateur)", verbose_name='Notes admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_requests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Demande d'impression",
                'verbose_name_plural': "Demandes d'impression",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_size', models.CharField(choices=[('10x15', '10x15 cm (0,50€)'), ('50x70', '50x70 cm (40,00€)'), ('other', 'Autre (à discuter)')], max_length=10, verbose_name="Format d'impression")),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('custom_size', models.CharField(blank=True, help_text='Si "Autre" est sélectionné, préciser le format souhaité', max_length=100, verbose_name='Format personnalisé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_items', to='galleries.image', verbose_name='Image')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='galleries.printrequest', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Article à imprimer',
                'verbose_name_plural': 'Articles à imprimer',
                'ordering': ['created_at'],
            },
        ),
    ]
